HSE_DB/config/routes.rb
Rails.application.routes.draw do
  resources :survey_question_responses
  resources :defense_responses
  resources :observations
  resources :customers
  resources :employee_observers
  resources :observation_types
  resources :regions
  resources :survey_questions
  resources :defenses
  resources :service_centers
  resources :business_units

end

HSE_DB/app/models/business_unit.rb
class BusinessUnit < ActiveRecord::Base
end

HSE_DB/app/models/customer.rb
class Customer < ActiveRecord::Base
end

HSE_DB/app/models/defense.rb
class Defense < ActiveRecord::Base
	has_many :defense_responses
end

HSE_DB/app/models/defense_response.rb
class DefenseResponse < ActiveRecord::Base
  belongs_to :observation
  belongs_to :defense
end

HSE_DB/app/models/employee_observer.rb
class EmployeeObserver < ActiveRecord::Base
  belongs_to :region
end

HSE_DB/app/models/observation.rb
class Observation < ActiveRecord::Base
  belongs_to :customer
  belongs_to :business_unit
  belongs_to :employee_observer
  belongs_to :region
  belongs_to :service_center
  belongs_to :observation_type
  has_many :survey_question_responses, :dependent => :delete_all
  has_many :defense_responses, :dependent => :delete_all

  accepts_nested_attributes_for :survey_question_responses
  accepts_nested_attributes_for :defense_responses
end

HSE_DB/app/models/observation_type.rb
class ObservationType < ActiveRecord::Base
end

HSE_DB/app/models/region.rb
class Region < ActiveRecord::Base
end

HSE_DB/app/models/service_center.rb
class ServiceCenter < ActiveRecord::Base
end

HSE_DB/app/models/survey_question.rb
class SurveyQuestion < ActiveRecord::Base
	has_many :survey_question_responses
end

HSE_DB/app/models/survey_question_response.rb
class SurveyQuestionResponse < ActiveRecord::Base
  belongs_to :observation
  belongs_to :survey_question
  
end

HSE_DB/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:company_name)
    end
end

HSE_DB/app/controllers/defenses_controller.rb
class DefensesController < ApplicationController
  before_action :set_defense, only: [:show, :edit, :update, :destroy]

  # GET /defenses
  # GET /defenses.json
  def index
    @defenses = Defense.all
  end

  # GET /defenses/1
  # GET /defenses/1.json
  def show
  end

  # GET /defenses/new
  def new
    @defense = Defense.new
  end

  # GET /defenses/1/edit
  def edit
  end

  # POST /defenses
  # POST /defenses.json
  def create
    @defense = Defense.new(defense_params)

    respond_to do |format|
      if @defense.save
        format.html { redirect_to @defense, notice: 'Defense was successfully created.' }
        format.json { render :show, status: :created, location: @defense }
      else
        format.html { render :new }
        format.json { render json: @defense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /defenses/1
  # PATCH/PUT /defenses/1.json
  def update
    respond_to do |format|
      if @defense.update(defense_params)
        format.html { redirect_to @defense, notice: 'Defense was successfully updated.' }
        format.json { render :show, status: :ok, location: @defense }
      else
        format.html { render :edit }
        format.json { render json: @defense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /defenses/1
  # DELETE /defenses/1.json
  def destroy
    @defense.destroy
    respond_to do |format|
      format.html { redirect_to defenses_url, notice: 'Defense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_defense
      @defense = Defense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def defense_params
      params.require(:defense).permit(:description)
    end
end

HSE_DB/app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:description)
    end
end

HSE_DB/app/helpers/application_helper.rb
module ApplicationHelper
end

HSE_DB/app/helpers/business_units_helper.rb
module BusinessUnitsHelper
end

HSE_DB/app/helpers/customers_helper.rb
module CustomersHelper
end

HSE_DB/app/helpers/defense_responses_helper.rb
module DefenseResponsesHelper
end

HSE_DB/app/helpers/defenses_helper.rb
module DefensesHelper
end

HSE_DB/app/helpers/observations_helper.rb
module ObservationsHelper
end

HSE_DB/app/helpers/regions_helper.rb
module RegionsHelper
end

HSE_DB/app/helpers/service_centers_helper.rb
module ServiceCentersHelper
end

HSE_DB/app/helpers/survey_questions_helper.rb
module SurveyQuestionsHelper
end

HSE_DB/app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HSE_DB/app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

HSE_DB/app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.company_name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

HSE_DB/app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

HSE_DB/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @customer.company_name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

HSE_DB/app/views/regions/_form.html.erb
<%= form_for(@region) do |f| %>
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% @region.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HSE_DB/app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form' %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

HSE_DB/app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Regions</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.description %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Region', new_region_path %>

HSE_DB/app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>

HSE_DB/app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @region.description %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>