HSE_DB/config/routes.rb
Rails.application.routes.draw do
  resources :survey_question_responses
  resources :defense_responses
  resources :observations
  resources :customers
  resources :employee_observers
  resources :observation_types
  resources :regions
  resources :survey_questions
  resources :defenses
  resources :service_centers
  resources :business_units

end

HSE_DB/app/models/survey_question.rb
class SurveyQuestion < ActiveRecord::Base
	has_many :survey_question_responses
end

HSE_DB/app/controllers/survey_questions_controller.rb
class SurveyQuestionsController < ApplicationController
  before_action :set_survey_question, only: [:show, :edit, :update, :destroy]

  # GET /survey_questions
  # GET /survey_questions.json
  def index
    @survey_questions = SurveyQuestion.all
  end

  # GET /survey_questions/1
  # GET /survey_questions/1.json
  def show
  end

  # GET /survey_questions/new
  def new
    @survey_question = SurveyQuestion.new
  end

  # GET /survey_questions/1/edit
  def edit
  end

  # POST /survey_questions
  # POST /survey_questions.json
  def create
    @survey_question = SurveyQuestion.new(survey_question_params)

    respond_to do |format|
      if @survey_question.save
        format.html { redirect_to @survey_question, notice: 'Survey question was successfully created.' }
        format.json { render :show, status: :created, location: @survey_question }
      else
        format.html { render :new }
        format.json { render json: @survey_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_questions/1
  # PATCH/PUT /survey_questions/1.json
  def update
    respond_to do |format|
      if @survey_question.update(survey_question_params)
        format.html { redirect_to @survey_question, notice: 'Survey question was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_question }
      else
        format.html { render :edit }
        format.json { render json: @survey_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_questions/1
  # DELETE /survey_questions/1.json
  def destroy
    @survey_question.destroy
    respond_to do |format|
      format.html { redirect_to survey_questions_url, notice: 'Survey question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_question
      @survey_question = SurveyQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_question_params
      params.require(:survey_question).permit(:question_text)
    end
end

HSE_DB/app/helpers/survey_questions_helper.rb
module SurveyQuestionsHelper
end

HSE_DB/app/views/survey_questions/_form.html.erb
<%= form_for(@survey_question) do |f| %>
  <% if @survey_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey_question.errors.count, "error") %> prohibited this survey_question from being saved:</h2>

      <ul>
      <% @survey_question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_text %><br>
    <%= f.text_field :question_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HSE_DB/app/views/survey_questions/edit.html.erb
<h1>Editing Survey Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey_question %> |
<%= link_to 'Back', survey_questions_path %>

HSE_DB/app/views/survey_questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Survey Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @survey_questions.each do |survey_question| %>
      <tr>
        <td><%= survey_question.question_text %></td>
        <td><%= link_to 'Show', survey_question %></td>
        <td><%= link_to 'Edit', edit_survey_question_path(survey_question) %></td>
        <td><%= link_to 'Destroy', survey_question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey question', new_survey_question_path %>

HSE_DB/app/views/survey_questions/new.html.erb
<h1>New Survey Question</h1>

<%= render 'form' %>

<%= link_to 'Back', survey_questions_path %>

HSE_DB/app/views/survey_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question text:</strong>
  <%= @survey_question.question_text %>
</p>

<%= link_to 'Edit', edit_survey_question_path(@survey_question) %> |
<%= link_to 'Back', survey_questions_path %>