HSE_DB/config/routes.rb
Rails.application.routes.draw do
  resources :survey_question_responses
  resources :defense_responses
  resources :observations
  resources :customers
  resources :employee_observers
  resources :observation_types
  resources :regions
  resources :survey_questions
  resources :defenses
  resources :service_centers
  resources :business_units

end

HSE_DB/app/models/observation.rb
class Observation < ActiveRecord::Base
  belongs_to :customer
  belongs_to :business_unit
  belongs_to :employee_observer
  belongs_to :region
  belongs_to :service_center
  belongs_to :observation_type
  has_many :survey_question_responses, :dependent => :delete_all
  has_many :defense_responses, :dependent => :delete_all

  accepts_nested_attributes_for :survey_question_responses
  accepts_nested_attributes_for :defense_responses
end

HSE_DB/app/models/observation_type.rb
class ObservationType < ActiveRecord::Base
end

HSE_DB/app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  before_action :set_observation, only: [:show, :edit, :update, :destroy]

  # GET /observations
  # GET /observations.json
  def index
    @observations = Observation.all
  end

  # GET /observations/1
  # GET /observations/1.json
  def show
  end

  # GET /observations/new
  def new
    @observation = Observation.new
    create_empty_question_set
    create_empty_defense_set
    set_available_dropdown_values

  end

  # GET /observations/1/edit
  def edit
    set_available_dropdown_values
  end

  # POST /observations
  # POST /observations.json
  def create
    @observation = Observation.new(observation_params)
    
    respond_to do |format|
      if @observation.save
        format.html { redirect_to @observation, notice: 'Observation was successfully created.' }
        format.json { render :show, status: :created, location: @observation }
      else
        format.html { render :new }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /observations/1
  # PATCH/PUT /observations/1.json
  def update

    respond_to do |format|
      if @observation.update(observation_params)
        format.html { redirect_to @observation, notice: 'Observation was successfully updated.' }
        format.json { render :show, status: :ok, location: @observation }
      else
        format.html { render :edit }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /observations/1
  # DELETE /observations/1.json
  def destroy
    @observation.destroy
    respond_to do |format|
      format.html { redirect_to observations_url, notice: 'Observation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_observation
      @observation = Observation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def observation_params
      params.require(:observation).permit(:description, :customer_id, :observation_date, :business_unit_id, :employee_observer_id, :region_id, :feedback_comments, :service_center_id, :observation_type_id,
        survey_question_responses_attributes: [:response, :observation_id, :id, :survey_question_id],
        defense_responses_attributes: [:response, :observation_id, :id, :defense_id])

    end

    def get_survey_quesiton_response_params
      survey_question_responses = Hash.new
      # for each question
      SurveyQuestion.all.collect.each do |q|
        #look up answer in hash if it exists
        if params.has_key? 'q_' + q.id.to_s
          #add response to hash of hashes
          survey_question_responses[q.id] = {:observation_id => @observation.id, :survey_question_id => q.id, :response => params['q_' + q.id.to_s]}
        end 
      end

      return survey_question_responses
    end

    def save_survey_question_responses(survey_question_responses_params)
      success = true

      survey_question_responses_params.each do |k, v|
        new_response = SurveyQuestionResponse.new(v)
        success = new_response.save and success
      end

    end

    def set_available_dropdown_values()
      @customers = Customer.all.collect{|c| [c.company_name, c.id]}
      @business_units = BusinessUnit.all.collect{|b| [b.description, b.id]}
      @employee_observers = EmployeeObserver.all.collect{|e| [e.first_name + " " + e.last_name, e.id]}
      @regions = Region.all.collect{|r| [r.description, r.id]} 
      @service_centers = ServiceCenter.all.collect{|s| [s.description, s.id]}
      @observation_types = ObservationType.all.collect{|o| [o.description, o.id]}

    end

    def create_empty_question_set()
      SurveyQuestion.all.collect.each do |q|
        @observation.survey_question_responses.new(survey_question_id: q.id)
      end
    end

    def create_empty_defense_set()
      Defense.all.collect.each do |d|
        @observation.defense_responses.new(defense_id: d.id)
      end
    end

end

HSE_DB/app/helpers/observations_helper.rb
module ObservationsHelper
end

HSE_DB/app/views/observations/_form.html.erb
<%= form_for(@observation) do |f| %>
  <% if @observation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@observation.errors.count, "error") %> prohibited this observation from being saved:</h2>

      <ul>
      <% @observation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.select :customer_id, @customers %>
  </div>
  <div class="field">
    <%= f.label :observation_date %><br>
    <%= f.datetime_select :observation_date %>
  </div>
  <div class="field">
    <%= f.label :business_unit_id %><br>
    <%= f.select :business_unit_id,  @business_units %>
  </div>
  <div class="field">
    <%= f.label :employee_observer_id %><br>
    <%= f.select :employee_observer_id, @employee_observers %>
  </div>
  <div class="field">
    <%= f.label :region_id %><br>
    <%= f.select :region_id, @regions %>
  </div>
  <div class="field">
    <%= f.label :feedback_comments %><br>
    <%= f.text_field :feedback_comments %>
  </div>
  <div class="field">
    <%= f.label :service_center_id %><br>
    <%= f.select :service_center_id, @service_centers %>
  </div>
  <div class="field">
    <%= f.label :observation_type_id %><br>
    <%= f.select :observation_type_id, @observation_types %>
  </div>

  <table border="1" class="questions">

  <%= f.fields_for :survey_question_responses do |sq| %>
  <tr>
    <td><%= sq.label sq.object.survey_question.question_text unless sq.object.survey_question.nil? %> </td>
    <td><%= sq.text_field :response %></td>
    <%= sq.hidden_field :survey_question_id %>
    <%= sq.hidden_field :id %>
  </tr>
  <% end %>

  </table>

  <table border="1" class="defenses">

  <%= f.fields_for :defense_responses do |dr| %>
  <tr>
    <td><%= dr.label dr.object.defense.description unless dr.object.defense.description.nil? %> </td>
    <td><%= dr.text_field :response %></td>
    <%= dr.hidden_field :defense_id %>
    <%= dr.hidden_field :id %>
  </tr>
  <% end %>

  </table>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HSE_DB/app/views/observations/edit.html.erb
<h1>Editing Observation</h1>

<%= render 'form' %>

<%= link_to 'Show', @observation %> |
<%= link_to 'Back', observations_path %>

HSE_DB/app/views/observations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Observations</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Customer</th>
      <th>Observation date</th>
      <th>Business unit</th>
      <th>Employee observer</th>
      <th>Region</th>
      <th>Feedback comments</th>
      <th>Service center</th>
      <th>Observation type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @observations.each do |observation| %>
      <tr>
        <td><%= observation.description %></td>
        <td><%= observation.customer %></td>
        <td><%= observation.observation_date %></td>
        <td><%= observation.business_unit %></td>
        <td><%= observation.employee_observer %></td>
        <td><%= observation.region %></td>
        <td><%= observation.feedback_comments %></td>
        <td><%= observation.service_center %></td>
        <td><%= observation.observation_type %></td>
        <td><%= link_to 'Show', observation %></td>
        <td><%= link_to 'Edit', edit_observation_path(observation) %></td>
        <td><%= link_to 'Destroy', observation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Observation', new_observation_path %>

HSE_DB/app/views/observations/new.html.erb
<h1>New Observation</h1>

<%= render 'form' %>

<%= link_to 'Back', observations_path %>

HSE_DB/app/views/observations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @observation.description %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @observation.customer %>
</p>

<p>
  <strong>Observation date:</strong>
  <%= @observation.observation_date %>
</p>

<p>
  <strong>Business unit:</strong>
  <%= @observation.business_unit %>
</p>

<p>
  <strong>Employee observer:</strong>
  <%= @observation.employee_observer %>
</p>

<p>
  <strong>Region:</strong>
  <%= @observation.region %>
</p>

<p>
  <strong>Feedback comments:</strong>
  <%= @observation.feedback_comments %>
</p>

<p>
  <strong>Service center:</strong>
  <%= @observation.service_center %>
</p>

<p>
  <strong>Observation type:</strong>
  <%= @observation.observation_type %>
</p>

<%= link_to 'Edit', edit_observation_path(@observation) %> |
<%= link_to 'Back', observations_path %>