HSE_DB/config/routes.rb
Rails.application.routes.draw do
  resources :survey_question_responses
  resources :defense_responses
  resources :observations
  resources :customers
  resources :employee_observers
  resources :observation_types
  resources :regions
  resources :survey_questions
  resources :defenses
  resources :service_centers
  resources :business_units

end

HSE_DB/app/models/business_unit.rb
class BusinessUnit < ActiveRecord::Base
end

HSE_DB/app/controllers/business_units_controller.rb
class BusinessUnitsController < ApplicationController
  before_action :set_business_unit, only: [:show, :edit, :update, :destroy]

  # GET /business_units
  # GET /business_units.json
  def index
    @business_units = BusinessUnit.all
  end

  # GET /business_units/1
  # GET /business_units/1.json
  def show
  end

  # GET /business_units/new
  def new
    @business_unit = BusinessUnit.new
  end

  # GET /business_units/1/edit
  def edit
  end

  # POST /business_units
  # POST /business_units.json
  def create
    @business_unit = BusinessUnit.new(business_unit_params)

    respond_to do |format|
      if @business_unit.save
        format.html { redirect_to @business_unit, notice: 'Business unit was successfully created.' }
        format.json { render :show, status: :created, location: @business_unit }
      else
        format.html { render :new }
        format.json { render json: @business_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_units/1
  # PATCH/PUT /business_units/1.json
  def update
    respond_to do |format|
      if @business_unit.update(business_unit_params)
        format.html { redirect_to @business_unit, notice: 'Business unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_unit }
      else
        format.html { render :edit }
        format.json { render json: @business_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_units/1
  # DELETE /business_units/1.json
  def destroy
    @business_unit.destroy
    respond_to do |format|
      format.html { redirect_to business_units_url, notice: 'Business unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_unit
      @business_unit = BusinessUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_unit_params
      params.require(:business_unit).permit(:description)
    end
end

HSE_DB/app/helpers/business_units_helper.rb
module BusinessUnitsHelper
end

HSE_DB/app/views/business_units/_form.html.erb
<%= form_for(@business_unit) do |f| %>
  <% if @business_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business_unit.errors.count, "error") %> prohibited this business_unit from being saved:</h2>

      <ul>
      <% @business_unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HSE_DB/app/views/business_units/edit.html.erb
<h1>Editing Business Unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @business_unit %> |
<%= link_to 'Back', business_units_path %>

HSE_DB/app/views/business_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Business Units</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_units.each do |business_unit| %>
      <tr>
        <td><%= business_unit.description %></td>
        <td><%= link_to 'Show', business_unit %></td>
        <td><%= link_to 'Edit', edit_business_unit_path(business_unit) %></td>
        <td><%= link_to 'Destroy', business_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business unit', new_business_unit_path %>

HSE_DB/app/views/business_units/new.html.erb
<h1>New Business Unit</h1>

<%= render 'form' %>

<%= link_to 'Back', business_units_path %>

HSE_DB/app/views/business_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @business_unit.description %>
</p>

<%= link_to 'Edit', edit_business_unit_path(@business_unit) %> |
<%= link_to 'Back', business_units_path %>